In [1]:
#range practice
#1 Print the numbers between 60 and 69 inclusive.

import numpy as np
number = np.arange(60,70)
print(number)

[60 61 62 63 64 65 66 67 68 69]


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [2]:
sum_of_squares = 0
total = 0
counter = 0
while (True):
    number = int(input('enter a number: '))
    if number == 0:
      break
    sum_of_squares += (number **2)
    total = total + number
    counter = counter + 1
   
mean=total/counter
print("mean is: "+ str(mean))

std= ((sum_of_squares/counter)-mean**2)**(1/2)
print("standard deviation is: "+ str(std))


enter a number: 10
enter a number: 20
enter a number: 0
mean is: 15.0
standard deviation is: 5.0


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [3]:
m_list = [2, 3, -2, -7, 0, 2, 3]

for item in m_list:
    if item % 2 != 0:
        print(item)

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [38]:

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def generate_primes(N):
    primes = []
    num = 2
    while len(primes) < N:
        if is_prime(num):
            primes.append(num)
        num += 1
    return primes

N = int(input("enter a number: "))
prime_list = generate_primes(int(N))
print(prime_list)





enter a number: 10
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.


In [37]:
def generate_fibonacii_series(n):
  a = 0
  b = 1
  my_list = []
  while b<n:
    my_list.append(b)
    temp = a
    a = b
    b = temp+b
  print(my_list)
  return my_list

def get_nth_fibonacci(my_new_list,position):
    print("Current List: "+str(my_new_list))
    print("The item in position "+str(position)+" is: "+str(my_new_list[position]))
    

number = int(input('Enter position to display the Content: '))
try:
    get_nth_fibonacci([20,1,2,4,5,7,8],number)
except IndexError:
    pass
else:
    AssertionError("TEST FAILS. Out of index index should raise a ValueError.")

Enter position to display the Content: 4
Current List: [20, 1, 2, 4, 5, 7, 8]
The item in position 4 is: 5


6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.

8. Use your reduce function for the following operations:

In [2]:
#a. Count the number of odd elements in a list of integers:
from functools import reduce

# Sample list of integers
integer_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Define a lambda function to count odd numbers
count_odd = lambda count, x: count + 1 if x % 2 != 0 else count

# Use reduce to count the odd numbers
odd_count = reduce(count_odd, integer_list, 0)

print("Number of odd elements:", odd_count)

#b. Find the maximum of a list of integers:
from functools import reduce

# Sample list of integers
integer_list = [34, 12, 56, 78, 23, 45, 67]

# Define a lambda function to find the maximum
find_max = lambda x, y: x if x > y else y

# Use reduce to find the maximum
max_value = reduce(find_max, integer_list)

print("Maximum value:", max_value)

#Find the longest string in a list of strings:
from functools import reduce

# Sample list of strings
string_list = ["apple", "banana", "cherry", "date", "elderberry"]

# Define a lambda function to find the longest string
find_longest = lambda x, y: x if len(x) > len(y) else y

# Use reduce to find the longest string
longest_string = reduce(find_longest, string_list)

print("Longest string:", longest_string)



Number of odd elements: 5
Maximum value: 78
Longest string: elderberry


9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

In [3]:
import numpy as np

def pairwise_l2_distance(matrix):
    # Get the number of rows in the matrix
    n = matrix.shape[0]
    
    # Initialize the output distance matrix
    distance_matrix = np.zeros((n, n))
    
    # Calculate the pairwise L2 distance for each row pair
    for i in range(n):
        for j in range(n):
            distance_matrix[i, j] = np.linalg.norm(matrix[i] - matrix[j])
    
    return distance_matrix


# Create a sample matrix A 
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the pairwise L2 distances
D = pairwise_l2_distance(A)

# Print the distance matrix
print(D)


[[ 0.          5.19615242 10.39230485]
 [ 5.19615242  0.          5.19615242]
 [10.39230485  5.19615242  0.        ]]


10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.
 

In [5]:
class A:
    def __init__(self, value):
        self.value = value
    
    def print_value(self):
        print("The stored value is:", self.value)

# Instantiate the class and call the print_value method
obj = A("abc")  # Creating an instance of class A with a value of abc
obj.print_value()  # Calling the print_value method to print the stored value


The stored value is: abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.


In [6]:
class B:
    def __init__(self, public_param, private_param):
        self.public_param = public_param
        self.__this_is_private = private_param

# Create an instance of the class
b_instance = B("Public Value", "Private Value")

# Check the __dict__ attribute of the instance
print(b_instance.__dict__)

# The mangled name of the private attribute can be found by adding an underscore and the class name before the attribute name:
mangled_name = b_instance._B__this_is_private
print("Mangled name of the private attribute:", mangled_name)


{'public_param': 'Public Value', '_B__this_is_private': 'Private Value'}
Mangled name of the private attribute: Private Value


13 . Inheritance

###### Guess the output without running the cell.

In [7]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [ ]:
class Animal:
    def __init__(self, age=0, number_of_legs=4):
        self.age = age
        self.number_of_legs = number_of_legs

    def make_sound(self):
        pass


class Cat(Animal):
    def __init__(self, age=0, number_of_legs=4, fur_color='unknown'):
        super().__init__(age, number_of_legs)
        if isinstance(fur_color, (list, tuple)):
            self.fur_color = fur_color
        else:
            self.fur_color = [fur_color]

    def make_sound(self):
        print("Meow!")


class Dog(Animal):
    def __init__(self, age=0, number_of_legs=4, fur_color='unknown'):
        super().__init__(age, number_of_legs)
        if isinstance(fur_color, (list, tuple)):
            self.fur_color = fur_color
        else:
            self.fur_color = [fur_color]

    def make_sound(self):
        print("Woof!")


class Fish(Animal):
    def __init__(self, age=0, number_of_legs=0):
        super().__init__(age, number_of_legs)

    def make_sound(self):
        print("Blub blub!")


class Eagle(Animal):
    def __init__(self, age=0, number_of_legs=2):
        super().__init__(age, number_of_legs)

    def make_sound(self):
        print("Screech!")


# Example usage:
cat = Cat(age=5, fur_color=['black', 'white'])
dog = Dog(age=3, fur_color='brown')
fish = Fish(age=1)
eagle = Eagle(age=10)

print(f"Cat age: {cat.age}, Fur colors: {', '.join(cat.fur_color)}")
print(f"Dog age: {dog.age}, Fur color: {', '.join(dog.fur_color)}")
print(f"Fish age: {fish.age}")
print(f"Eagle age: {eagle.age}")

cat.make_sound()
dog.make_sound()
fish.make_sound()
eagle.make_sound()
